### PR TITLE
Support for there being space delimited values in DRBD_MINOR

### PR DESCRIPTION
**Pull request by mattwillsher**
As discussed on IRC, theses are the changes to support space delimited values, as happens with volumes in 8.4

### CODE REVIEW

**Comment by mattwillsher** [comment]
Hi @digimer ,

Any chance of this getting merged?

**Comment by digimer** [comment]
Oh wow, I totally forgot about this.

I will try to flare up a couple VMs and install/test 8.4 this weekend. Please throw tomatoes at me if you haven't heard anything by Monday or Tuesday. Thanks!

**Comment by mattwillsher** [comment]
It's been winking at me on and off - figured it was time to give it a kick :)

**Comment by digimer** [comment]
Just a quick note; I've not forgotten this. I got swamped, but hope to test this coming week. I had conflicting changes, which I've already sorted out. I just need to test against 8.3.x, 8.4.x with and without volumes.

**Comment by digimer** [comment]
@mattwillsher 

So I finally got a chance to test this against 8.4 and it seems to work well. Sorry I didn't pull your version, I'm not the best at git and I had conflicts with some other changes I had made. I tried to give you credit in the git commit though. If you get a chance to test it, I'd love to hear back from you. :)

Thanks!!

**Pull request closed without merging**
